@startuml
skinparam svgDimensionStyle false
title Push HIE Flow
participant "Source" as Source
participant "Health Information Exchange" as HIE [[https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html HIE-Whitepaper]]
participant "Destination" as Destination
autonumber
activate Source
activate HIE
activate Destination

group Patient Discovery (PD)
note right of Source: e.g. XCPD, PDQ*, PIX*, PMIR
    Source -> HIE: Patient Lookup by Demographics
    Note left of Source: Provide whatever details are known
    Source <- HIE: Here are closest matches
    Source -> Source: Review results for best match
end group

group Alternative 1.1: Point-to-Point 
note right of Source: E.g. XDR, XDM/e-mail (aka Direct Project), and 360X
    Source -> Destination: Push document to Destination
    activate Destination
    Source <-- Destination: Success
    Destination -> Destination: Utilize document to treat patient
    deactivate Destination
end group
group Alternative 1.2: HIE mediated Push
note right of Source: E.g. XDR, and XCDR
    Source -> HIE: Push document to Destination
    HIE -> Destination: Push document to Destination
    activate Destination
    HIE <-- Destination: Success
    Source <-- HIE: Success
    Destination -> Destination: Utilize document to treat patient
    deactivate Destination
end group
@enduml
