@startuml
skinparam svgDimensionStyle false
title Publication HIE flow
participant "Source" as Source
participant "Health Information Exchange" as HIE [[https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html HIE-Whitepaper]]
participant "Destination" as Destination
autonumber
activate Source
activate HIE
activate Destination

group Patient Discovery (PD)
Source -> HIE: Patient Lookup by Demographics
Note left of Source: Provide whatever details are known
Source <- HIE: Here are closest matches
Source -> Source: Review results for best match
end group

group Alternative 1 Push (PD)
Source -> HIE: Push document to Destination
HIE -> Destination: Push to the Destination
activate Destination
HIE <-- Destination: Success
Source <-- HIE: Success
Destination -> Destination: utilize Document to treat patient
deactivate Destination
end group

group Alternative 2 Publish and notify (PN)
Source -> Source: Persist locally
Source -> Source: Have Metadata ready

Source --> Destination: notify the document is ready
activate Destination

group Query for Documents (QD)
Destination -> HIE: Look for the document
Note left of Destination: Query would use info from the notification step to get specific results
HIE -> Source: Do you have this document
HIE <-- Source: Yes, here is the metadata
Destination <-- HIE: Here is the document metadata
Destination -> Destination: could confirm the recommended\n document metadata is the one
end group

group Retrieve Document (RD)
Destination -> HIE: Retrieve this Document
HIE -> Source: Retrieve this Document
HIE <-- Source: Here is the Document
Destination <-- HIE: Here is the Documet
Destination -> Destination: utilize Document to treat patient
end group
deactivate Destination
end group

deactivate HIE
deactivate Source

@enduml
