@startuml
title Paramedicine Care flow
participant "Ambulance" as Ambulance
participant "Health Information Exchange" as HIE [[https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html HIE-Whitepaper]]
autonumber
activate Ambulance
activate HIE
Ambulance -> HIE: Get Medical Summary
Note left of Ambulance: Query for classCode=LOINC 34133-9\nLikely OnDemand Document Entry
Ambulance <-- HIE: Here is the latest Medical Summary
Note left of Ambulance: [[https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_TF_Vol1.pdf#nameddest=4_Exchange_of_Personal_Health_R CCD / IHE-XPHR]], [[https://www.hl7.org/ccdasearch/ C-CDA]] or [[https://hl7.org/fhir/uv/ips/ IPS]]

Ambulance -> Ambulance: utalize Medical Summary to treat patient

activate Hospital
Ambulance -> Hospital: Push Transport Summary 
Note left of Ambulance: [[https://www.ihe.net//uploadedFiles/Documents/PCC/IHE_PCC_Suppl_PCS.pdf IHE-Paramedicine Care Summary (PCS)]]

Ambulance -> Hospital: drop off Patient at ED

Hospital-> Hospital: Admit patient

Hospital -> Ambulance: Admit details

Ambulance -> HIE: Query, is the patient discharged yet? 
Note left of Ambulance: Query for classCode=LOINC 18842-5\nbetter - serviceStartTime=(time patient was dropped off)\nbest - referenceIdList=(admit detail)
Ambulance <-- HIE: Not yet

Hospital -> Hospital: Discarge Patient
Hospital -> HIE: Publish Discharge Summary
deactivate Hospital

Ambulance -> HIE: Query for Discarge Summary
Ambulance <-- HIE: Here is the Discarge Summary details
Note left of Ambulance: [[https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_TF_Vol1.pdf#nameddest=3_4_2_2_Discharge_Summary_Optio XDS-MS Discharge Summary Option]] or \n[[https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.1.8.html C-CDA Discharge Summary Option]]
deactivate HIE

Ambulance -> Ambulance: extract some elements
Ambulance -> Ambulance: Insert the received outcome data into the existing NEMSIS PCR
Note left of Ambulance: [[https://nemsis.org/technical-resources NEMSIS PCR]]
Ambulance -> State: Deliver NEMSIS report and Discharge Summary to the state

deactivate Ambulance

@enduml
