@startuml
skinparam svgDimensionStyle false
title General HIE flow
participant "Consumer" as Consumer
participant "Health Information Exchange" as HIE [[https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html HIE-Whitepaper]]
autonumber
activate Consumer
activate HIE

group Patient Discovery (PD)
Consumer -> HIE: Patient Lookup by Demographics
Note left of Consumer: Provide whatever details are known
Consumer <- HIE: Here are closest matches
Consumer -> Consumer: Review results for best match
end group

group Query for Documents (QD)
Consumer -> HIE: Look for Medical Summary
Note left of Consumer: Query for classCode=LOINC 34133-9\nLikely OnDemand Document Entry
Consumer <-- HIE: Here is the list of possible Medical Summary(s)
Note left of Consumer: [[https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_TF_Vol1.pdf#nameddest=4_Exchange_of_Personal_Health_R CCD / IHE-XPHR]], [[https://www.hl7.org/ccdasearch/ C-CDA]] or [[https://hl7.org/fhir/uv/ips/ IPS]]
Consumer -> Consumer: pick the freshest or best entry from available document entries
end group

group Retrieve Document (RD)
Consumer -> HIE: Retrieve this Document
Consumer -> Consumer: utilize Medical Summary to treat patient
end group

deactivate HIE
deactivate Consumer

@enduml
